version: "2"
services:
    docker-node-api:
        environment:
            - NODE_ENV=test
            # Use different db for testing
            - MONGO_URI=mongodb://mongo:27017/docker-node-api-test 
        command: yarn test